### ISSUE TITLE
Something wrong with theme

### ISSUE THREAD

**Issue by Exbilar** [casouri/lunarymacs#18]
error details on macOS:
`error: Font not available, #<font-spec nil nil SF Pro Text nil nil light nil nil 13.5 nil nil nil nil>`

**Comment by casouri** [comment]
Hi, that's because this snippet in init.el:

```
(when window-system
  (luna-load-font)
  (luna-load-cjk-font))
```

`luna-load-font` loads the first element of `luna-font-alist` if no `luna-font` is set in custom file.
On my machine I use SF Mono for Emacs, and you don't have it installed. I suggest adding an entry to `luna-font-alist` and load that font. If you put the font at the beginning of `luna-font-alist`, `luna-load-font` will load that instead. Or you can call `luna-set-font` interactively to set a font persistently.

**Comment by casouri** [comment]
Ima close this
